### PR TITLE
add configure to support bytecode systems, DESTDIR and install prefix

### PR DESCRIPTION
**Pull request by hendriktews**
Hi Daniel,

I expanded your topkg free build and install patch a little bit. Your version could be used, but has the following problems:
- no proper DESTDIR support
- no default install prefix
- limited support for bytecode architectures
- fails if installation directories do not exist

This is my proposal, let me know what you think.

Hendrik

### CODE REVIEW

**Comment by dbuenzli** [comment]
I'm not going to add a 150 lines `configure` shell script, use `sed` and and whatever for something that simple. A single `Makefile` should perfectly be able to handle this.

> no proper DESTDIR support

If the `DESTDIR` support is wrongly done I'm my proposal please adjust it in the original `Makefile`.

> no default install prefix

I'm not sure exactly why you need one but this can be adjusted in the original `Makefile`

> limited support for bytecode architectures

I'm not sure what you mean here. The appropriate targets are here you can invoke them according to your wishes.

> fails if installation directories do not exist

I see you now use `install` everywhere I didn't do this because on osx this installs only executables I guess this fixes it so why not.

**Comment by hendriktews** [comment]
Daniel Bünzli <notifications@github.com> writes:

> I'm not going to add a 150 lines configure shell script, use sed and
> and whatever for something that simple.

What is the problem? The detection of prerequisites (which takes
most of the 150 lines)? The shell? sed? Do you want everything
just in the makefile?

> I'm not sure what you mean here. The appropriate targets are here you

A proper installation procedure detects itself what to compile
and what to install and does not rely on external intelligence.

**Comment by dbuenzli** [comment]
> What is the problem?

Occam's razor is not being applied.

> A proper installation procedure detects itself what to compile
> and what to install and does not rely on external intelligence.

That's a point of view. I personally see little interest in doing so if the tool I'm using do not provide this support themselves in a generic fashion (which unfortunately `make` and `ocamlbuild` do not provide and those are the tools used for now). For this reasons:

1. You are essentially duplicating information that is in the `opam` file and/or in the build system and hardcoding discovery procedures in the package that should be provided by a library of some sort.
2. I think that the need for people to install `cmdliner` without a package manager of some sort is rather low. The package manager is able to provide that intelligence through its package constraints and build system invocation which allows me to circumvent the weakness of the tools in a sustainable fashion maintenance-wise.

I think that people who are constantly trying to tell me that it has no cost to add this ad-hoc script/Makefile here and there for convenience do not understand what it means to try to scale the development and maintenance of software packages.

So please simply alter in the most minimal fashion the `Makefile` to address the valid points you make. Regarding the byte and native you may be able to discover this by simply including `$(ocamlc -where)/Makefile.config`.

**Comment by dbuenzli** [comment]
I want to move forward on this. I think I addressed most of your points in the `Makefile` via 12137454cd135282ae29d20a3723cc7. Tell me in https://github.com/dbuenzli/cmdliner/issues/86 if further adjustements are needed and/or when you want a release.

**Comment by hendriktews** [comment]
> I want to move forward on this. I think I addressed most of your
> points in the Makefile via 1213745.

Thanks! Please see PR #88 - there I added proper support for
DESTDIR.

Hendrik

**Comment by hendriktews** [comment]
Hi Daniel,

> I think that people who are constantly trying to tell me that it has

I would appreciate if you could realize that I was never trying
to tell you something. If you need to make this statement, please
do it in a channel that addresses the right people.

Hendrik

**Comment by dbuenzli** [comment]
> I would appreciate if you could realize that I was never trying to tell you something.

Sorry, I didn't mean to say this.

**Pull request closed without merging**
